#!/bin/bash
# build_mode15_sidecar.sh -- compiles + (where safe) runs the mode-1.5
# step-1 sidecar deliverables:
#   - mode15_reader.h/.c (the container-reader module) +
#     tests/test_mode15_reader.c, against SYNTHETIC fixtures generated by
#     tests/gen_mode15_reader_fixtures.py (tools/mode15_container.py's own
#     encoder, reused unmodified) -- compiled AND RUN, tiny synthetic
#     data, instant.
#   - bench-m5max/mode15-falsifiers/two_queue_probe.mm -- compiled and
#     FULLY LINKED to prove it builds, NEVER executed (no GPU dispatch in
#     that file has ever run; see its own header comment for the
#     operator's real run commands).
#
# Scope matches this script's hard constraints: brief cc/clang compiles of
# small standalone files, tiny unit tests on synthetic data at nice -19.
# Never runs the engine, never touches /path/to/models, never executes
# any Metal/GPU code.
#
# Usage: bash c/tools/build_mode15_sidecar.sh [--keep-tmp]
set -euo pipefail

CDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"   # c/
cd "$CDIR"

KEEP_TMP=0
[[ "${1:-}" == "--keep-tmp" ]] && KEEP_TMP=1

CC="${CC:-cc}"
CLANGXX="${CLANGXX:-clang++}"
PYTHON="${PYTHON:-python3}"
TMPDIR_="$(mktemp -d "${TMPDIR:-/tmp}/mode15_sidecar.XXXXXX")"
cleanup(){ [[ "$KEEP_TMP" == 1 ]] || rm -rf "$TMPDIR_"; }
trap cleanup EXIT

log(){ echo "[build_mode15_sidecar $(date '+%H:%M:%S')] $*"; }

log "scratch dir: $TMPDIR_ $( [[ "$KEEP_TMP" == 1 ]] && echo '(kept on exit)' )"

# ---- 1. synthetic fixtures (tools/mode15_container.py's real encoder) ----
FIXDIR="$TMPDIR_/fixtures"
log "generating synthetic mode-1.5 fixtures -> $FIXDIR"
"$PYTHON" tests/gen_mode15_reader_fixtures.py "$FIXDIR"

# ---- 2. compile the reader + its unit test (plain C11, no engine deps) ----
TESTBIN="$TMPDIR_/test_mode15_reader"
log "compiling mode15_reader.c + tests/test_mode15_reader.c -> $TESTBIN"
"$CC" -std=c11 -O1 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function \
  mode15_reader.c tests/test_mode15_reader.c -o "$TESTBIN"

# ---- 3. run it (tiny, synthetic, instant -- explicitly allowed) ----
log "running unit tests at nice -19 (tiny synthetic data, instant)"
nice -n 19 "$TESTBIN" "$FIXDIR"
log "reader unit tests: PASS"

# ---- 4. two-queue GPU screening probe: COMPILE+LINK ONLY, NEVER RUN ----
PROBE="bench-m5max/mode15-falsifiers/two_queue_probe.mm"
PROBEBIN="$TMPDIR_/two_queue_probe"
if [[ -f "$PROBE" ]]; then
  log "compile-checking $PROBE (full link, NOT run -- see the probe's own"
  log "  header comment / bench-m5max/mode15-falsifiers/README.md for the"
  log "  operator's real run commands)"
  "$CLANGXX" -x objective-c++ -fobjc-arc -O3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function \
    "$PROBE" -framework Metal -framework Foundation -o "$PROBEBIN"
  log "compiled+linked OK -> $PROBEBIN (NEVER executed, per this script's GPU-execution ban)"
else
  log "WARNING: $PROBE not found -- skipping probe compile-check"
fi

log "ALL SIDECAR CHECKS PASSED (reader unit tests ran and passed; probe compiled+linked but never executed)"
