/* Forced-miss microbench: staged (gate+up / down concurrent) vs today's
 * single coalesced ~18.9MB read, swept over concurrency depth 1/2/4 -- the
 * n2 falsifier's own spec (docs/performance-theory.json,
 * n2-staged-intra-expert-streaming: "a forced-miss microbench ... swept
 * over NVMe queue depths 1/2/4 ... the load-bearing unknown"). Depth here
 * doubles as BOTH axes the entry names: how many experts miss together in
 * one MoE layer-step (n2's target regime is M<=2) AND how many concurrent
 * reads a real NVMe queue sees -- each concurrently-loaded expert in this
 * microbench IS a missed expert, so depth=1/2/4 sweeps both at once.
 *
 * Every load targets a FRESH, never-resident ESlot (memset, eid=-1) --
 * "forced miss" by construction, not by evicting a real cache. Runnable
 * later on the real model (SNAP=<real container dir>) and dry-runnable
 * today on the tiny numpy fixture (SNAP=<dir built by
 * tests/tiny_serve_fixture.py>) -- the forced-miss mechanism and the
 * depth sweep are identical either way; only the ABSOLUTE numbers become
 * representative once run against real NVMe (this file makes no
 * performance claim on the tiny fixture -- see the printed disclaimer).
 *
 * Usage:
 *   make staged-read-microbench
 *   ./tests/staged_expert_read_microbench <SNAP dir> [layer] [reps]
 *
 * GLM_STAGED_INCLUDE lets tests drive this against an arbitrary patched
 * engine source (default: the checked-in lab variant, generated by `make
 * glm_m5max_staged.c`); tests/test_patch_m5max_staged_expert_read.py passes
 * an absolute temp path here to dry-run against a freshly-patched source
 * without touching the committed tree. */
#define main ili_glm_main_unused
#ifndef GLM_STAGED_INCLUDE
#define GLM_STAGED_INCLUDE "../glm_m5max_staged.c"
#endif
#include GLM_STAGED_INCLUDE
#undef main

#include <stdio.h>

static int mb_cmp_double(const void *a, const void *b){
    double x=*(const double*)a, y=*(const double*)b;
    return x<y ? -1 : x>y ? 1 : 0;
}
static double median(double *v, int n){
    qsort(v,n,sizeof(double),mb_cmp_double);
    return n&1 ? v[n/2] : (v[n/2-1]+v[n/2])/2.0;
}

typedef struct { Model *m; int layer, eid; ESlot *slot; int staged; } LoadJob;

static void *run_one_job(void *arg){
    LoadJob *j=(LoadJob*)arg;
    /* force cold: a never-touched slot, no slab/fslab carried over from any
     * earlier trial (a stale slab_cap could let a load skip its own
     * allocation path, which is fine for correctness but would be an unfair
     * timing advantage for whichever mode happens to run second). */
    memset(j->slot,0,sizeof(*j->slot)); j->slot->eid=-1;
    if(j->staged){
        StagedLoad sl;
        expert_load_staged_begin(j->m,j->layer,j->eid,j->slot,1,&sl);
        /* "start their computation when ready": gate+up are fully loaded the
         * instant begin() returns, so any gate/up-dependent work belongs
         * HERE, genuinely concurrent with down's still-in-flight background
         * read -- this microbench's own compute stand-in (see main()'s
         * COMPUTE_STANDIN_FLOPS note) runs at exactly this point in the
         * caller-side loop below, not inside this helper. */
        expert_load_staged_join(&sl);
    } else {
        expert_load(j->m,j->layer,j->eid,j->slot,1);
    }
    return NULL;
}

/* One trial: `depth` experts loaded CONCURRENTLY (one pthread per expert).
 * Returns wall-clock seconds for the whole batch (not per-expert -- the
 * caller reports both). */
static double time_batch(Model *m, int layer, const int *eids, ESlot *slots, int depth, int staged){
    pthread_t th[64]; LoadJob jobs[64];
    double t0=now_s();
    for(int i=0;i<depth;i++){
        jobs[i].m=m; jobs[i].layer=layer; jobs[i].eid=eids[i]; jobs[i].slot=&slots[i]; jobs[i].staged=staged;
        if(pthread_create(&th[i],NULL,run_one_job,&jobs[i])!=0){ perror("pthread_create"); exit(1); }
    }
    for(int i=0;i<depth;i++) pthread_join(th[i],NULL);
    return now_s()-t0;
}

int main(int argc, char **argv){
    if(argc<2){
        fprintf(stderr,"usage: %s <SNAP dir> [layer] [reps]\n",argv[0]);
        fprintf(stderr,"  layer: routed MoE layer to target (default: first sparse layer found)\n");
        fprintf(stderr,"  reps:  trials per depth (default 9; median reported)\n");
        return 2;
    }
    const char *snap=argv[1];
    int want_layer = argc>2 ? atoi(argv[2]) : -1;
    int reps = argc>3 ? atoi(argv[3]) : 9;
    if(reps<1) reps=1;

    g_drop=1;              /* DONTNEED after every read: forced-miss stays forced across trials */
    g_mmap=0;               /* staging has no mmap fast path -- see the patch's module docstring */

    Model m;
    model_init(&m,snap,8,8,8);

    int layer=-1;
    for(int i=0;i<m.c.n_layers;i++) if(m.L[i].sparse){ layer = (want_layer>=0) ? want_layer : i; break; }
    if(layer<0 || !m.L[layer].sparse){
        fprintf(stderr,"no routed MoE layer available (or --layer %d is not sparse)\n",layer);
        return 1;
    }
    int n_experts = m.c.n_experts;
    printf("[staged-read-microbench] SNAP=%s layer=%d n_experts=%d reps=%d\n",snap,layer,n_experts,reps);
    printf("[staged-read-microbench] DISCLAIMER: absolute timings are only representative "
           "on real NVMe against the real container; on a tiny fixture this validates the "
           "MECHANISM (correctness + the depth sweep), not a performance verdict.\n");

    int depths[] = {1,2,4};
    for(int di=0; di<3; di++){
        int depth = depths[di];
        if(depth > n_experts){
            printf("depth=%d: skipped (fixture has only %d experts)\n",depth,n_experts);
            continue;
        }
        int eids[64]; for(int i=0;i<depth;i++) eids[i]=i%n_experts;
        ESlot slots[64]; memset(slots,0,sizeof(slots));

        double single_t[64], staged_t[64];
        for(int r=0;r<reps;r++) single_t[r]=time_batch(&m,layer,eids,slots,depth,0);
        for(int i=0;i<depth;i++){ compat_aligned_free(slots[i].slab); free(slots[i].fslab); }
        memset(slots,0,sizeof(slots));
        for(int r=0;r<reps;r++) staged_t[r]=time_batch(&m,layer,eids,slots,depth,1);
        for(int i=0;i<depth;i++){ compat_aligned_free(slots[i].slab); free(slots[i].fslab); }

        double single_med=median(single_t,reps), staged_med=median(staged_t,reps);
        double delta_pct = single_med>0 ? 100.0*(single_med-staged_med)/single_med : 0.0;
        printf("depth=%d: single-read median %.6fs | staged median %.6fs | delta %+.1f%% "
               "(positive = staged faster)\n", depth, single_med, staged_med, delta_pct);
    }
    return 0;
}
