/* tests/test_metal_row_decode.mm -- standalone Metal GPU probe for the
 * mode-3 / mode-1.5 codec-race follow-up (docs/PERFORMANCE_THEORY.md n1:
 * "n1_codec_race_requirement" / "n1_row_independent_coding_caveat_for_mode3").
 *
 * CONTEXT. the codec-race results measured the CPU
 * scalar-C reference decode of all four row-independent int4 entropy codecs
 * (c/codec_row_huff.h, c/codec_row_rans.h, c/codec_row_fse.h,
 * c/codec_row_bitplane.h) and found all three real compressors 36-50x too
 * slow to fuse into a GEMV dequant loop even at the easier miss-path budget
 * -- winner rANS-4way: 1.46 GB/s @ 18 threads vs the ~51 GB/s raw int4
 * nibble-unpack baseline (bitplane+exception's raw-passthrough fallback
 * number, i.e. today's matmul_i4/qt_addrow dequant speed). That merge's own
 * commit message: "container target reverts to case-D int2-only (+33%)
 * unless a Metal row-decoder probe (preregistered budget) surprises."
 * THIS FILE is that probe.
 *
 * SCOPE. Standalone -- new files only (this file + its Makefile target),
 * does NOT touch backend_metal.mm (owned by other in-flight work this
 * session). Own device/queue/library/pipelines, own synthetic census-shaped
 * test data, generated by SAMPLING a quantized-Gaussian distribution (the
 * same family/bisection-on-sigma approach as
 * c/tools/gen_codec_race_synthetic.py's dist_for_entropy, reimplemented
 * here in C++ since this is a standalone .mm with no Python dependency) and
 * then encoded through the ACTUAL MERGED C ENCODER -- c/codec_row_huff.h's
 * huff_build()/huff_encode_row() and c/codec_row_bitplane.h's
 * bitplane_build()/bitplane_encode_row(), plus c/codec_row.h's RowOffsets --
 * not a reimplementation of the codec. Only the GPU decode kernels below
 * are new logic; the bitstreams they consume come from the same header
 * files codec_race.c and the unit tests already exercise on CPU, so a
 * GPU/CPU decode mismatch below is a Metal-side bug, not a data-generation
 * artifact.
 *
 * PREREGISTERED VERDICT LINES (fixed by the task prompt before any kernel
 * in this file was written or run -- see also
 * the Metal row-decode results, whose header states
 * these same two lines ahead of its measured section):
 *
 *   (A) mode-1.5 REVIVED if sustained (steady-state, 1000-iteration)
 *       canonical-Huffman decode-ONLY throughput >= 10 GB/s (raw bytes/s,
 *       the same 0.5-bytes/symbol convention as the CPU study and
 *       codec_race.c: raw_bytes = total_rows * (I/2)).
 *   (B) mode-3 VIABLE if fused decode+GEMV throughput >= 60% of the plain
 *       int4-unpack+GEMV baseline's throughput, same corpus/shape, same
 *       steady-state convention.
 *   Anything less on a line = that mode is DEAD on this hardware for this
 *   format; less on BOTH = entropy coding is DEAD on this hardware, full
 *   stop, record the numbers.
 *
 * WHAT THIS MEASURES (five Metal compute kernels, one MSL library):
 *  1. huff_decode_rows: canonical-Huffman decode via a wide LUT staged
 *     into threadgroup memory once per row-batch (one threadgroup per
 *     ILI_ROWS_PER_TG-row batch, one thread per row -- decode is an
 *     inherently serial bit-walk per row since codeword length is data-
 *     dependent, so row-level parallelism across thousands of independent
 *     GPU threads is the only parallelism a row-CODED format can offer;
 *     that is exactly what this kernel/benchmark measures). The LUT is
 *     cooperatively copied from device memory into threadgroup memory once
 *     per threadgroup (every thread in the batch then does its OWN row's
 *     lookups against the on-chip copy) -- the whole point of staging it
 *     is to turn "one device-memory load per symbol lookup" into "one
 *     device-memory load per LUT entry per threadgroup, then N_symbols
 *     on-chip lookups."
 *  2. int4_unpack_rows: the plain fixed-stride nibble-unpack baseline --
 *     today's matmul_i4/qt_addrow dequant (see c/codec_row_gemv.h's file
 *     header for the exact call sites), same row-per-thread shape, no
 *     bitstream/no LUT, fixed-stride addressing.
 *  3. huff_decode_gemv_fused / int4_gemv_fused_baseline: the mode-3 shape
 *     itself -- decode (or unpack) a row and immediately dot-product it
 *     against a shared activation vector, one thread per output row,
 *     accumulate-as-you-decode (no separate materialize-then-multiply
 *     pass -- each symbol is consumed by an FMA the instant it is decoded),
 *     exactly the fusion c/codec_row_gemv.h sketches in scalar C for the
 *     CPU side.
 *  4. bitplane_decode_rows (the OPTIONAL second format, branchless/
 *     predicated decode -- no LUT, no data-dependent branch, a fixed-cost
 *     gather+select per symbol): included to show the pipeline shape of
 *     the "GPU-oriented exact" candidate. Run on two corpora: the main
 *     census-shaped one (H~2.9 bits/weight, where the CPU study found the
 *     codebook selector correctly falls back to raw passthrough -- expect
 *     the same here) and a separate, deliberately lower-entropy corpus
 *     (forces a narrow base-plane window so the rank-indexed exception
 *     gather is genuinely exercised, not just the degenerate branch).
 *
 * All decode kernels are checked bit-exact against the matching CPU
 * reference decoder (codec_row_huff.h's huff_decode_row /
 * codec_row_bitplane.h's bitplane_decode_row, called directly, unmodified)
 * before any timing number is trusted; the two fused-GEMV kernels are
 * checked against a CPU double-precision reference dot product. Any
 * mismatch is a hard failure (non-zero exit) -- see run_correctness().
 *
 * Build/run: `make metal-row-decode-test` (from c/). No /path/to/models
 * reads. GPU fixture runs only (synthetic data, single process) -- no
 * engine-idle gating needed.
 */
#import <Metal/Metal.h>
#import <Foundation/Foundation.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <cstdint>
#include <vector>
#include <functional>
#include <algorithm>

#include "../codec_row.h"
#include "../codec_row_huff.h"
#include "../codec_row_bitplane.h"

/* ============================================================ constants */
static const uint32_t ILI_I_SYMBOLS       = 6144;   /* gate/up row width, codec_row.h */
static const uint32_t ILI_ROWS_PER_EXPERT = 2048;   /* gate/up O, codec_row.h */
static const uint32_t ILI_N_SYNTH_EXPERTS = 8;      /* -> 16384 rows total: "thousands of rows" */
static const uint32_t ILI_ROWS_PER_TG     = 256;    /* threads per threadgroup = rows per batch */
static const double   ILI_H_TARGET_GATEUP = 2.90;   /* bits/weight, matches census gate/up h_global */
static const uint64_t ILI_SEED            = 20260715ULL;

static const uint32_t ILI_PEAKED_ROWS = 256;        /* small corpus to exercise bitplane's exception path */
static const double   ILI_PEAKED_H    = 1.00;       /* bits/weight: narrow enough to force base_bits<4 */

static uint32_t env_u32(const char *name, uint32_t def){
    const char *v = getenv(name);
    if(!v || !*v) return def;
    long x = strtol(v, NULL, 10);
    return x>0 ? (uint32_t)x : def;
}

/* ================================================================ MSL == */
static const char *ROW_DECODE_SHADER = R"METAL(
#include <metal_stdlib>
using namespace metal;

struct HuffParams     { uint total_rows; uint I; uint maxlen; uint lut_size; };
struct RowParams       { uint total_rows; uint I; };
struct BitplaneParams { uint total_rows; uint I; uint base_bits; uint bias; };

// -- (1) canonical Huffman decode, wide LUT cooperatively staged into
// threadgroup memory once per row-batch; one thread decodes one row's
// entire bitstream (inherently serial: codeword length is data-dependent).
kernel void huff_decode_rows(
    device const uchar *payload      [[buffer(0)]],
    device const uint  *row_offsets  [[buffer(1)]],
    device const uchar *lut_global   [[buffer(2)]],
    device uchar       *out_symbols  [[buffer(3)]],
    constant HuffParams &p           [[buffer(4)]],
    threadgroup uchar  *lut_tg       [[threadgroup(0)]],
    uint tid     [[thread_position_in_threadgroup]],
    uint tg_size [[threads_per_threadgroup]],
    uint row     [[thread_position_in_grid]])
{
    for (uint idx = tid; idx < p.lut_size; idx += tg_size) lut_tg[idx] = lut_global[idx];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (row >= p.total_rows) return;

    uint pos = row_offsets[row];
    uint end = row_offsets[row+1];
    ulong acc = 0; int nbits = 0;
    uint maxlen = p.maxlen;
    device uchar *out_row = out_symbols + (ulong)row * p.I;

    for (uint i = 0; i < p.I; i++) {
        while (nbits < (int)maxlen && pos < end) { acc |= (ulong)payload[pos] << nbits; pos++; nbits += 8; }
        uint window = (uint)(acc & (((ulong)1 << maxlen) - 1));
        uchar entry = lut_tg[window];
        uchar sym = entry & 0xF;
        uchar len = entry >> 4;
        out_row[i] = sym;
        acc >>= len; nbits -= (int)len;
    }
}

// -- (2) plain fixed-stride int4 nibble unpack: the matmul_i4/qt_addrow
// baseline, one thread per row, no bitstream/no LUT.
kernel void int4_unpack_rows(
    device const uchar *flat_packed [[buffer(0)]],
    device uchar       *out_symbols [[buffer(1)]],
    constant RowParams &p           [[buffer(2)]],
    uint row [[thread_position_in_grid]])
{
    if (row >= p.total_rows) return;
    uint row_bytes = p.I >> 1;
    device const uchar *w = flat_packed + (ulong)row * row_bytes;
    device uchar *out_row = out_symbols + (ulong)row * p.I;
    for (uint i = 0; i < p.I; i += 2) {
        uchar b = w[i>>1];
        out_row[i]   = b & 0xF;
        out_row[i+1] = b >> 4;
    }
}

// -- (3a) mode-3 shape: Huffman-decode a row and immediately FMA each
// symbol against the shared activation vector x[I] -- decode and consume
// are the SAME loop, nothing materialized row-wide first.
kernel void huff_decode_gemv_fused(
    device const uchar *payload      [[buffer(0)]],
    device const uint  *row_offsets  [[buffer(1)]],
    device const uchar *lut_global   [[buffer(2)]],
    device const float *x            [[buffer(3)]],
    device const float *scale        [[buffer(4)]],
    device float       *y            [[buffer(5)]],
    constant HuffParams &p           [[buffer(6)]],
    threadgroup uchar  *lut_tg       [[threadgroup(0)]],
    uint tid     [[thread_position_in_threadgroup]],
    uint tg_size [[threads_per_threadgroup]],
    uint row     [[thread_position_in_grid]])
{
    for (uint idx = tid; idx < p.lut_size; idx += tg_size) lut_tg[idx] = lut_global[idx];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (row >= p.total_rows) return;

    uint pos = row_offsets[row];
    uint end = row_offsets[row+1];
    ulong acc = 0; int nbits = 0;
    uint maxlen = p.maxlen;
    float a = 0.0f;

    for (uint i = 0; i < p.I; i++) {
        while (nbits < (int)maxlen && pos < end) { acc |= (ulong)payload[pos] << nbits; pos++; nbits += 8; }
        uint window = (uint)(acc & (((ulong)1 << maxlen) - 1));
        uchar entry = lut_tg[window];
        uchar sym = entry & 0xF;
        uchar len = entry >> 4;
        float v = (float)((int)sym - 8);          // same signed dequant as qt_addrow's (b&0xF)-8
        a += v * x[i];
        acc >>= len; nbits -= (int)len;
    }
    y[row] = a * scale[row];
}

// -- (3b) plain-int4-unpack GEMV baseline, same fused shape as (3a) but
// reading directly from the flat fixed-stride packed array.
kernel void int4_gemv_fused_baseline(
    device const uchar *flat_packed [[buffer(0)]],
    device const float *x           [[buffer(1)]],
    device const float *scale       [[buffer(2)]],
    device float       *y           [[buffer(3)]],
    constant RowParams &p           [[buffer(4)]],
    uint row [[thread_position_in_grid]])
{
    if (row >= p.total_rows) return;
    uint row_bytes = p.I >> 1;
    device const uchar *w = flat_packed + (ulong)row * row_bytes;
    float a = 0.0f;
    for (uint i = 0; i < p.I; i += 2) {
        uchar b = w[i>>1];
        int v0 = (int)(b & 0xF) - 8;
        int v1 = (int)(b >> 4) - 8;
        a += (float)v0 * x[i] + (float)v1 * x[i+1];
    }
    y[row] = a * scale[row];
}

// -- (4) branchless bitplane+exception decode: fixed per-position cost
// (k base bits + 1 mask bit + an unconditional rank-indexed exception-area
// gather + a bitmask select, no data-dependent branch), mirroring
// codec_row_bitplane.h's bitplane_decode_row exactly. base_bits==4 is the
// raw-passthrough fallback (native packed nibbles, no header). No LUT/no
// threadgroup memory needed -- one thread per row.
kernel void bitplane_decode_rows(
    device const uchar *payload       [[buffer(0)]],
    device const uint  *row_offsets   [[buffer(1)]],
    device uchar       *out_symbols   [[buffer(2)]],
    constant BitplaneParams &p        [[buffer(3)]],
    uint row [[thread_position_in_grid]])
{
    if (row >= p.total_rows) return;
    uint off = row_offsets[row];
    uint end = row_offsets[row+1];
    device const uchar *rowptr = payload + off;
    uint paylen = end - off;
    device uchar *out_row = out_symbols + (ulong)row * p.I;
    uint n = p.I;

    if (p.base_bits == 4) {
        for (uint i = 0; i < n; i += 2) {
            uchar b = rowptr[i>>1];
            out_row[i]   = b & 0xF;
            out_row[i+1] = b >> 4;
        }
        return;
    }

    uint k = p.base_bits;
    uint base_bytes = (n*k + 7) / 8;
    uint mask_bytes  = (n + 7) / 8;
    uint off_base = 2, off_mask = off_base + base_bytes, off_exc = off_mask + mask_bytes;

    ulong acc_b = 0; int nbits_b = 0; uint pos_b = off_base;
    ulong acc_m = 0; int nbits_m = 0; uint pos_m = off_mask;
    uint exc_len = (paylen > off_exc) ? (paylen - off_exc) : 0;
    uint rank = 0;

    for (uint i = 0; i < n; i++) {
        while (nbits_b < (int)k && pos_b < off_mask) { acc_b |= (ulong)rowptr[pos_b] << nbits_b; pos_b++; nbits_b += 8; }
        uint code = (uint)(acc_b & ((1u<<k)-1u));
        acc_b >>= k; nbits_b -= (int)k;

        while (nbits_m < 1 && pos_m < off_exc) { acc_m |= (ulong)rowptr[pos_m] << nbits_m; pos_m++; nbits_m += 8; }
        uint is_exc = (uint)(acc_m & 1u);
        acc_m >>= 1; nbits_m -= 1;

        uint byte_idx = rank >> 1;
        uchar packed_byte = (byte_idx < exc_len) ? rowptr[off_exc + byte_idx] : 0;
        uchar exc_val = ((rank & 1u) == 0) ? (uchar)(packed_byte & 0xF) : (uchar)(packed_byte >> 4);
        uchar base_val = (uchar)(code + p.bias);
        uchar sel = (uchar)0 - (uchar)is_exc;                 // 0x00 or 0xFF, branchless select
        out_row[i] = (uchar)((exc_val & sel) | (base_val & (uchar)~sel));
        rank += is_exc;
    }
}
)METAL";

/* ======================================================= host-side C++ */
struct HuffParamsHost     { uint32_t total_rows, I, maxlen, lut_size; };
struct RowParamsHost      { uint32_t total_rows, I; };
struct BitplaneParamsHost { uint32_t total_rows, I, base_bits, bias; };

/* xorshift64* -- deterministic, seeded, no platform-dependent behavior
 * (unlike rand()/srand()); only needed for reproducible synthetic data. */
struct RNG {
    uint64_t s;
    explicit RNG(uint64_t seed) : s(seed ? seed : 0x9E3779B97F4A7C15ULL) {}
    uint64_t next(){ s ^= s<<13; s ^= s>>7; s ^= s<<17; return s; }
    double uniform01(){ return (double)(next()>>11) * (1.0/9007199254740992.0); } /* 53-bit mantissa in [0,1) */
};

/* Same quantized-Gaussian family + bisection-on-sigma as
 * tools/gen_codec_race_synthetic.py's dist_for_entropy(), reimplemented
 * here in C++ (no Python dependency in a standalone .mm probe). Peaked at
 * symbol 8 (value = symbol-8), matching glm.c's signed int4 convention. */
static void gaussian_pmf(double sigma, double p[16]){
    double tot=0;
    for(int i=0;i<16;i++){ double x=(double)i-8.0; p[i]=exp(-(x*x)/(2.0*sigma*sigma)); tot+=p[i]; }
    for(int i=0;i<16;i++) p[i]/=tot;
}
static double entropy_of_pmf(const double p[16]){
    double h=0; for(int i=0;i<16;i++) if(p[i]>0) h -= p[i]*log2(p[i]);
    return h;
}
static void dist_for_entropy(double target_h, double p_out[16]){
    target_h = std::min(3.999, std::max(0.02, target_h));
    double lo=0.06, hi=200.0, p_lo[16], p_hi[16];
    gaussian_pmf(lo,p_lo); gaussian_pmf(hi,p_hi);
    if (entropy_of_pmf(p_lo) >= target_h){ memcpy(p_out,p_lo,sizeof(p_lo)); return; }
    if (entropy_of_pmf(p_hi) <= target_h){ memcpy(p_out,p_hi,sizeof(p_hi)); return; }
    double mid[16]; memcpy(mid,p_lo,sizeof(mid));
    for(int it=0; it<60; it++){
        double mids=(lo+hi)/2.0;
        gaussian_pmf(mids, mid);
        double h=entropy_of_pmf(mid);
        if (fabs(h-target_h) <= 1e-4) break;
        if (h < target_h) lo=mids; else hi=mids;
    }
    memcpy(p_out, mid, sizeof(mid));
}
static void sample_symbols_row(const double p[16], uint32_t n, RNG &rng, uint8_t *out){
    double cdf[17]; cdf[0]=0;
    for(int i=0;i<16;i++) cdf[i+1]=cdf[i]+p[i];
    for(uint32_t i=0;i<n;i++){
        double u = rng.uniform01() * cdf[16];
        int s=0; while(s<15 && cdf[s+1] < u) s++;
        out[i]=(uint8_t)s;
    }
}

static void die(const char *what, NSError *err){
    fprintf(stderr, "test_metal_row_decode: %s%s%s\n", what,
            err ? ": " : "", err ? [[err localizedDescription] UTF8String] : "");
    exit(1);
}

struct Ctx {
    id<MTLDevice> dev;
    id<MTLCommandQueue> q;
    id<MTLComputePipelineState> huff_decode, huff_gemv, int4_decode, int4_gemv, bitplane_decode;
};

static Ctx setup(){
    Ctx c{};
    c.dev = MTLCreateSystemDefaultDevice();
    if(!c.dev) die("no Metal device", nil);
    c.q = [c.dev newCommandQueue];
    NSError *err = nil;
    id<MTLLibrary> lib = [c.dev newLibraryWithSource:[NSString stringWithUTF8String:ROW_DECODE_SHADER]
                                              options:nil error:&err];
    if(!lib) die("shader compile failed", err);
    auto P = [&](const char *name) -> id<MTLComputePipelineState> {
        id<MTLFunction> f = [lib newFunctionWithName:[NSString stringWithUTF8String:name]];
        if(!f){ fprintf(stderr, "missing function %s\n", name); exit(1); }
        NSError *e2 = nil;
        id<MTLComputePipelineState> pso = [c.dev newComputePipelineStateWithFunction:f error:&e2];
        if(!pso) die(name, e2);
        return pso;
    };
    c.huff_decode     = P("huff_decode_rows");
    c.huff_gemv       = P("huff_decode_gemv_fused");
    c.int4_decode     = P("int4_unpack_rows");
    c.int4_gemv       = P("int4_gemv_fused_baseline");
    c.bitplane_decode = P("bitplane_decode_rows");
    return c;
}

/* Runs `iters` timed dispatches (after `warmup` untimed ones); returns
 * {best, mean} GPU-side seconds/iter (cb.GPUEndTime-cb.GPUStartTime, this
 * codebase's own convention -- see tests/test_score_stage_prefalsifier.mm --
 * for isolating kernel cost from CPU-side encode/submit latency). */
struct BenchTime { double best_s, mean_s; };
static BenchTime bench_dispatch(id<MTLCommandQueue> q, int warmup, int iters,
                                 const std::function<void(id<MTLComputeCommandEncoder>)> &encode){
    auto dispatch_once = [&]() -> id<MTLCommandBuffer> {
        id<MTLCommandBuffer> cb = [q commandBuffer];
        id<MTLComputeCommandEncoder> e = [cb computeCommandEncoder];
        encode(e);
        [e endEncoding];
        [cb commit];
        return cb;
    };
    for(int i=0;i<warmup;i++){ id<MTLCommandBuffer> cb=dispatch_once(); [cb waitUntilCompleted]; }
    double total=0.0, best=1e300;
    for(int i=0;i<iters;i++){
        id<MTLCommandBuffer> cb = dispatch_once();
        [cb waitUntilCompleted];
        if(cb.status == MTLCommandBufferStatusError)
            die("command buffer execution failed", cb.error);
        double dt = [cb GPUEndTime] - [cb GPUStartTime];
        total += dt;
        if(dt < best) best = dt;
    }
    BenchTime r; r.best_s = best; r.mean_s = total/iters;
    return r;
}

static double raw_bytes_for(uint64_t total_rows, uint64_t I){ return (double)total_rows * (double)(I/2); }
static double ns_per_4kb(double gbps){ return gbps>0 ? 4096.0/gbps : 0.0; }

struct KernelBench { std::string name; double single_gbps=0, steady_gbps=0; };

int main(void){
@autoreleasepool {
    Ctx c = setup();
    fprintf(stderr, "device: %s | maxThreadgroupMemoryLength=%lu | maxThreadsPerThreadgroup=%lu\n",
            [c.dev.name UTF8String], (unsigned long)c.dev.maxThreadgroupMemoryLength,
            (unsigned long)c.dev.maxThreadsPerThreadgroup.width);

    const uint32_t I = ILI_I_SYMBOLS;
    const uint32_t TOTAL_ROWS = env_u32("ILI_ROW_DECODE_ROWS", ILI_ROWS_PER_EXPERT*ILI_N_SYNTH_EXPERTS);
    const uint32_t STEADY_ITERS = env_u32("ILI_ROW_DECODE_STEADY_ITERS", 1000);
    fprintf(stderr, "corpus: %u rows x %u symbols/row (gate/up shape), target H=%.3f bits/weight, steady_iters=%u\n",
            TOTAL_ROWS, I, ILI_H_TARGET_GATEUP, STEADY_ITERS);

    /* ---------------------------------------------- 1. synthetic corpus */
    double pmf[16]; dist_for_entropy(ILI_H_TARGET_GATEUP, pmf);
    RNG rng(ILI_SEED);
    std::vector<uint8_t> symbols((size_t)TOTAL_ROWS * I);
    for(uint32_t r=0;r<TOTAL_ROWS;r++) sample_symbols_row(pmf, I, rng, &symbols[(size_t)r*I]);

    uint32_t counts[16]; codec_histogram(symbols.data(), (int)((size_t)TOTAL_ROWS*I), counts);
    double achieved_h = codec_entropy_bits(counts);
    fprintf(stderr, "achieved corpus entropy: %.4f bits/weight (target %.3f)\n", achieved_h, ILI_H_TARGET_GATEUP);

    /* --------------------------------------- 2. Huffman-encode (real C encoder) */
    HuffCodebook hcb; huff_build(counts, &hcb);
    fprintf(stderr, "huffman codebook: maxlen=%d n_present=%d lut_bytes=%d\n",
            hcb.maxlen, hcb.n_present, 1<<hcb.maxlen);
    if((size_t)(1<<hcb.maxlen) > c.dev.maxThreadgroupMemoryLength){
        fprintf(stderr, "FATAL: LUT (%d bytes) exceeds device threadgroup memory (%lu bytes)\n",
                1<<hcb.maxlen, (unsigned long)c.dev.maxThreadgroupMemoryLength);
        return 1;
    }
    std::vector<uint8_t> huff_lut((size_t)1<<hcb.maxlen);
    for(size_t i=0;i<huff_lut.size();i++){
        HuffLutEnt e = hcb.lut[i];
        huff_lut[i] = (uint8_t)((e.sym & 0xF) | (e.len << 4));
    }

    RowOffsets huff_ro; row_offsets_init(&huff_ro, TOTAL_ROWS);
    std::vector<uint8_t> huff_payload; huff_payload.reserve((size_t)TOTAL_ROWS*(I/2));
    {
        std::vector<uint8_t> tmp((size_t)I*2);
        for(uint32_t r=0;r<TOTAL_ROWS;r++){
            size_t used = huff_encode_row(&hcb, &symbols[(size_t)r*I], (int)I, tmp.data(), tmp.size());
            if(used == (size_t)-1){ fprintf(stderr, "huffman encode overflow at row %u\n", r); return 1; }
            huff_payload.insert(huff_payload.end(), tmp.begin(), tmp.begin()+used);
            row_offsets_push(&huff_ro, (uint32_t)used);
        }
    }
    fprintf(stderr, "huffman: %zu payload bytes (ratio incl. row_offsets/codebook not counted here; "
                     "see results.md for the CPU study's own ratio numbers on this codec)\n", huff_payload.size());

    /* --------------------------------------- 3. flat int4 baseline (same data) */
    std::vector<uint8_t> flat_packed((size_t)TOTAL_ROWS*(I/2));
    for(uint32_t r=0;r<TOTAL_ROWS;r++)
        codec_pack_nibbles(&symbols[(size_t)r*I], (int)I, &flat_packed[(size_t)r*(I/2)]);

    /* --------------------------------------- 4. bitplane: main corpus + peaked corpus */
    BitplaneCodebook bcb_main; bitplane_build(counts, &bcb_main);
    RowOffsets bp_ro_main; row_offsets_init(&bp_ro_main, TOTAL_ROWS);
    std::vector<uint8_t> bp_payload_main; bp_payload_main.reserve((size_t)TOTAL_ROWS*(I/2)+64);
    {
        std::vector<uint8_t> tmp((size_t)I+16);
        for(uint32_t r=0;r<TOTAL_ROWS;r++){
            size_t used = bitplane_encode_row(&bcb_main, &symbols[(size_t)r*I], (int)I, tmp.data(), tmp.size());
            if(used == (size_t)-1){ fprintf(stderr, "bitplane encode overflow (main) at row %u\n", r); return 1; }
            bp_payload_main.insert(bp_payload_main.end(), tmp.begin(), tmp.begin()+used);
            row_offsets_push(&bp_ro_main, (uint32_t)used);
        }
    }
    fprintf(stderr, "bitplane (main corpus): base_bits=%d bias=%d (4=raw-passthrough fallback)\n",
            bcb_main.base_bits, bcb_main.bias);

    /* peaked corpus: deliberately lower entropy so the (k<4) exception-gather
     * branch is genuinely exercised, not just the raw-passthrough fallback. */
    double pmf_peaked[16]; dist_for_entropy(ILI_PEAKED_H, pmf_peaked);
    std::vector<uint8_t> symbols_peaked((size_t)ILI_PEAKED_ROWS*I);
    for(uint32_t r=0;r<ILI_PEAKED_ROWS;r++) sample_symbols_row(pmf_peaked, I, rng, &symbols_peaked[(size_t)r*I]);
    uint32_t counts_peaked[16]; codec_histogram(symbols_peaked.data(), (int)((size_t)ILI_PEAKED_ROWS*I), counts_peaked);
    BitplaneCodebook bcb_peaked; bitplane_build(counts_peaked, &bcb_peaked);
    RowOffsets bp_ro_peaked; row_offsets_init(&bp_ro_peaked, ILI_PEAKED_ROWS);
    std::vector<uint8_t> bp_payload_peaked; bp_payload_peaked.reserve((size_t)ILI_PEAKED_ROWS*I);
    {
        std::vector<uint8_t> tmp((size_t)I+16);
        for(uint32_t r=0;r<ILI_PEAKED_ROWS;r++){
            size_t used = bitplane_encode_row(&bcb_peaked, &symbols_peaked[(size_t)r*I], (int)I, tmp.data(), tmp.size());
            if(used == (size_t)-1){ fprintf(stderr, "bitplane encode overflow (peaked) at row %u\n", r); return 1; }
            bp_payload_peaked.insert(bp_payload_peaked.end(), tmp.begin(), tmp.begin()+used);
            row_offsets_push(&bp_ro_peaked, (uint32_t)used);
        }
    }
    fprintf(stderr, "bitplane (peaked corpus, H=%.3f): base_bits=%d bias=%d -- %s\n",
            ILI_PEAKED_H, bcb_peaked.base_bits, bcb_peaked.bias,
            bcb_peaked.base_bits<4 ? "exercises exception-gather branch" : "STILL degenerate, raise ILI_PEAKED_H down further");

    /* ---------------------------------------- 5. activation vector + scales */
    std::vector<float> x_host(I), scale_host(TOTAL_ROWS);
    for(uint32_t i=0;i<I;i++) x_host[i] = (float)(rng.uniform01()*2.0-1.0);
    for(uint32_t r=0;r<TOTAL_ROWS;r++) scale_host[r] = (float)(0.5 + rng.uniform01());

    /* CPU double-precision GEMV reference (ground truth for both fused kernels) */
    std::vector<float> y_ref(TOTAL_ROWS);
    for(uint32_t r=0;r<TOTAL_ROWS;r++){
        double acc=0; const uint8_t *srow=&symbols[(size_t)r*I];
        for(uint32_t i=0;i<I;i++) acc += (double)((int)srow[i]-8) * (double)x_host[i];
        y_ref[r] = (float)(acc * scale_host[r]);
    }

    /* --------------------------------------------------- 6. GPU buffers */
    id<MTLDevice> dev = c.dev;
    auto mkbuf = [&](const void *bytes, size_t len) -> id<MTLBuffer> {
        id<MTLBuffer> b = len>0 ? [dev newBufferWithBytes:bytes length:len options:MTLResourceStorageModeShared]
                                 : [dev newBufferWithLength:4 options:MTLResourceStorageModeShared];
        if(!b) die("buffer allocation failed", nil);
        return b;
    };
    auto mkbuf_len = [&](size_t len) -> id<MTLBuffer> {
        id<MTLBuffer> b = [dev newBufferWithLength:len options:MTLResourceStorageModeShared];
        if(!b) die("buffer allocation failed", nil);
        return b;
    };

    id<MTLBuffer> b_huff_payload = mkbuf(huff_payload.data(), huff_payload.size());
    id<MTLBuffer> b_huff_offsets = mkbuf(huff_ro.offsets, (size_t)(huff_ro.n_rows+1)*sizeof(uint32_t));
    id<MTLBuffer> b_huff_lut     = mkbuf(huff_lut.data(), huff_lut.size());
    id<MTLBuffer> b_flat_packed  = mkbuf(flat_packed.data(), flat_packed.size());
    id<MTLBuffer> b_bp_payload_m = mkbuf(bp_payload_main.data(), bp_payload_main.size());
    id<MTLBuffer> b_bp_offsets_m = mkbuf(bp_ro_main.offsets, (size_t)(bp_ro_main.n_rows+1)*sizeof(uint32_t));
    id<MTLBuffer> b_bp_payload_p = mkbuf(bp_payload_peaked.data(), bp_payload_peaked.size());
    id<MTLBuffer> b_bp_offsets_p = mkbuf(bp_ro_peaked.offsets, (size_t)(bp_ro_peaked.n_rows+1)*sizeof(uint32_t));
    id<MTLBuffer> b_x            = mkbuf(x_host.data(), x_host.size()*sizeof(float));
    id<MTLBuffer> b_scale        = mkbuf(scale_host.data(), scale_host.size()*sizeof(float));

    id<MTLBuffer> b_out_huff  = mkbuf_len((size_t)TOTAL_ROWS*I);
    id<MTLBuffer> b_out_int4  = mkbuf_len((size_t)TOTAL_ROWS*I);
    id<MTLBuffer> b_out_bp_m  = mkbuf_len((size_t)TOTAL_ROWS*I);
    id<MTLBuffer> b_out_bp_p  = mkbuf_len((size_t)ILI_PEAKED_ROWS*I);
    id<MTLBuffer> b_y_huff    = mkbuf_len((size_t)TOTAL_ROWS*sizeof(float));
    id<MTLBuffer> b_y_int4    = mkbuf_len((size_t)TOTAL_ROWS*sizeof(float));

    HuffParamsHost hp{ TOTAL_ROWS, I, (uint32_t)hcb.maxlen, (uint32_t)(1u<<hcb.maxlen) };
    RowParamsHost  rp{ TOTAL_ROWS, I };
    BitplaneParamsHost bpp_main{ TOTAL_ROWS, I, (uint32_t)bcb_main.base_bits, (uint32_t)bcb_main.bias };
    BitplaneParamsHost bpp_peaked{ ILI_PEAKED_ROWS, I, (uint32_t)bcb_peaked.base_bits, (uint32_t)bcb_peaked.bias };
    size_t lut_tg_alloc = (((size_t)hp.lut_size + 15)/16)*16;
    if(lut_tg_alloc < 16) lut_tg_alloc = 16;

    /* -------------------------------------------------- 7. correctness */
    bool ok = true;
    auto report_mismatch = [&](const char *what){ fprintf(stderr, "CORRECTNESS FAILURE: %s\n", what); ok=false; };

    /* 7a. huff_decode_rows vs CPU reference AND original symbols */
    bench_dispatch(c.q, 0, 1, [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.huff_decode];
        [e setBuffer:b_huff_payload offset:0 atIndex:0];
        [e setBuffer:b_huff_offsets offset:0 atIndex:1];
        [e setBuffer:b_huff_lut offset:0 atIndex:2];
        [e setBuffer:b_out_huff offset:0 atIndex:3];
        [e setBytes:&hp length:sizeof(hp) atIndex:4];
        [e setThreadgroupMemoryLength:lut_tg_alloc atIndex:0];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(ILI_ROWS_PER_TG,1,1)];
    });
    {
        const uint8_t *gpu = (const uint8_t*)b_out_huff.contents;
        std::vector<uint8_t> cpu_ref(I);
        size_t mism_vs_cpu=0, mism_vs_orig=0;
        for(uint32_t r=0;r<TOTAL_ROWS;r++){
            size_t off=huff_ro.offsets[r], len=huff_ro.offsets[r+1]-off;
            huff_decode_row(&hcb, huff_payload.data()+off, len, (int)I, cpu_ref.data());
            if(memcmp(cpu_ref.data(), gpu+(size_t)r*I, I)!=0) mism_vs_cpu++;
            if(memcmp(&symbols[(size_t)r*I], gpu+(size_t)r*I, I)!=0) mism_vs_orig++;
        }
        fprintf(stderr, "[huff_decode_rows] rows checked=%u mismatch_vs_CPU_reference=%zu mismatch_vs_original=%zu\n",
                TOTAL_ROWS, mism_vs_cpu, mism_vs_orig);
        if(mism_vs_cpu || mism_vs_orig) report_mismatch("huff_decode_rows GPU output != CPU reference / original");
    }

    /* 7b. int4_unpack_rows vs original */
    bench_dispatch(c.q, 0, 1, [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.int4_decode];
        [e setBuffer:b_flat_packed offset:0 atIndex:0];
        [e setBuffer:b_out_int4 offset:0 atIndex:1];
        [e setBytes:&rp length:sizeof(rp) atIndex:2];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
    });
    {
        const uint8_t *gpu = (const uint8_t*)b_out_int4.contents;
        size_t mism = memcmp(gpu, symbols.data(), (size_t)TOTAL_ROWS*I)==0 ? 0 : 1;
        fprintf(stderr, "[int4_unpack_rows] bulk-memcmp-vs-original mismatch=%zu\n", mism);
        if(mism) report_mismatch("int4_unpack_rows GPU output != original");
    }

    /* 7c. huff_decode_gemv_fused vs CPU double-precision reference */
    bench_dispatch(c.q, 0, 1, [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.huff_gemv];
        [e setBuffer:b_huff_payload offset:0 atIndex:0];
        [e setBuffer:b_huff_offsets offset:0 atIndex:1];
        [e setBuffer:b_huff_lut offset:0 atIndex:2];
        [e setBuffer:b_x offset:0 atIndex:3];
        [e setBuffer:b_scale offset:0 atIndex:4];
        [e setBuffer:b_y_huff offset:0 atIndex:5];
        [e setBytes:&hp length:sizeof(hp) atIndex:6];
        [e setThreadgroupMemoryLength:lut_tg_alloc atIndex:0];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(ILI_ROWS_PER_TG,1,1)];
    });
    {
        const float *gpu = (const float*)b_y_huff.contents;
        double max_abs=0, max_ref=0;
        for(uint32_t r=0;r<TOTAL_ROWS;r++){ max_abs=std::max(max_abs,(double)fabsf(gpu[r]-y_ref[r])); max_ref=std::max(max_ref,(double)fabsf(y_ref[r])); }
        double relerr = max_abs/(max_ref+1e-9);
        fprintf(stderr, "[huff_decode_gemv_fused] max_abs_diff=%.6g relerr=%.3e\n", max_abs, relerr);
        if(relerr > 1e-3) report_mismatch("huff_decode_gemv_fused vs CPU reference exceeds tolerance");
    }

    /* 7d. int4_gemv_fused_baseline vs the SAME CPU reference */
    bench_dispatch(c.q, 0, 1, [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.int4_gemv];
        [e setBuffer:b_flat_packed offset:0 atIndex:0];
        [e setBuffer:b_x offset:0 atIndex:1];
        [e setBuffer:b_scale offset:0 atIndex:2];
        [e setBuffer:b_y_int4 offset:0 atIndex:3];
        [e setBytes:&rp length:sizeof(rp) atIndex:4];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
    });
    {
        const float *gpu = (const float*)b_y_int4.contents;
        double max_abs=0, max_ref=0;
        for(uint32_t r=0;r<TOTAL_ROWS;r++){ max_abs=std::max(max_abs,(double)fabsf(gpu[r]-y_ref[r])); max_ref=std::max(max_ref,(double)fabsf(y_ref[r])); }
        double relerr = max_abs/(max_ref+1e-9);
        fprintf(stderr, "[int4_gemv_fused_baseline] max_abs_diff=%.6g relerr=%.3e\n", max_abs, relerr);
        if(relerr > 1e-3) report_mismatch("int4_gemv_fused_baseline vs CPU reference exceeds tolerance");
    }

    /* 7e. bitplane_decode_rows -- main corpus (expected degenerate raw-passthrough) */
    bench_dispatch(c.q, 0, 1, [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.bitplane_decode];
        [e setBuffer:b_bp_payload_m offset:0 atIndex:0];
        [e setBuffer:b_bp_offsets_m offset:0 atIndex:1];
        [e setBuffer:b_out_bp_m offset:0 atIndex:2];
        [e setBytes:&bpp_main length:sizeof(bpp_main) atIndex:3];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
    });
    {
        const uint8_t *gpu = (const uint8_t*)b_out_bp_m.contents;
        std::vector<uint8_t> cpu_ref(I);
        size_t mism_vs_cpu=0, mism_vs_orig=0;
        for(uint32_t r=0;r<TOTAL_ROWS;r++){
            size_t off=bp_ro_main.offsets[r], len=bp_ro_main.offsets[r+1]-off;
            bitplane_decode_row(&bcb_main, bp_payload_main.data()+off, len, (int)I, cpu_ref.data());
            if(memcmp(cpu_ref.data(), gpu+(size_t)r*I, I)!=0) mism_vs_cpu++;
            if(memcmp(&symbols[(size_t)r*I], gpu+(size_t)r*I, I)!=0) mism_vs_orig++;
        }
        fprintf(stderr, "[bitplane_decode_rows/main] rows checked=%u mismatch_vs_CPU_reference=%zu mismatch_vs_original=%zu\n",
                TOTAL_ROWS, mism_vs_cpu, mism_vs_orig);
        if(mism_vs_cpu || mism_vs_orig) report_mismatch("bitplane_decode_rows (main corpus) GPU output != CPU reference / original");
    }

    /* 7f. bitplane_decode_rows -- peaked corpus (exercises the exception-gather branch) */
    bench_dispatch(c.q, 0, 1, [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.bitplane_decode];
        [e setBuffer:b_bp_payload_p offset:0 atIndex:0];
        [e setBuffer:b_bp_offsets_p offset:0 atIndex:1];
        [e setBuffer:b_out_bp_p offset:0 atIndex:2];
        [e setBytes:&bpp_peaked length:sizeof(bpp_peaked) atIndex:3];
        [e dispatchThreads:MTLSizeMake(ILI_PEAKED_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
    });
    {
        const uint8_t *gpu = (const uint8_t*)b_out_bp_p.contents;
        std::vector<uint8_t> cpu_ref(I);
        size_t mism_vs_cpu=0, mism_vs_orig=0, total_exceptions=0;
        for(uint32_t r=0;r<ILI_PEAKED_ROWS;r++){
            size_t off=bp_ro_peaked.offsets[r], len=bp_ro_peaked.offsets[r+1]-off;
            bitplane_decode_row(&bcb_peaked, bp_payload_peaked.data()+off, len, (int)I, cpu_ref.data());
            if(memcmp(cpu_ref.data(), gpu+(size_t)r*I, I)!=0) mism_vs_cpu++;
            if(memcmp(&symbols_peaked[(size_t)r*I], gpu+(size_t)r*I, I)!=0) mism_vs_orig++;
            uint16_t n_exc; memcpy(&n_exc, bp_payload_peaked.data()+off, sizeof(uint16_t));
            total_exceptions += n_exc;
        }
        fprintf(stderr, "[bitplane_decode_rows/peaked] rows checked=%u mismatch_vs_CPU_reference=%zu mismatch_vs_original=%zu "
                        "total_exceptions=%zu (branch genuinely exercised: %s)\n",
                ILI_PEAKED_ROWS, mism_vs_cpu, mism_vs_orig, total_exceptions,
                (bcb_peaked.base_bits<4 && total_exceptions>0) ? "yes" : "NO -- see warning above");
        if(mism_vs_cpu || mism_vs_orig) report_mismatch("bitplane_decode_rows (peaked corpus) GPU output != CPU reference / original");
    }

    if(!ok){
        fprintf(stderr, "\ncorrectness FAILED -- refusing to report timing numbers as meaningful.\n");
        return 1;
    }
    fprintf(stderr, "\nall correctness checks PASSED (GPU decode bit-exact vs CPU reference on every kernel).\n\n");

    /* -------------------------------------------------------- 8. bench */
    double raw_bytes = raw_bytes_for(TOTAL_ROWS, I);
    std::vector<KernelBench> results;

    auto run_bench = [&](const char *name, const std::function<void(id<MTLComputeCommandEncoder>)> &enc) {
        BenchTime single = bench_dispatch(c.q, 3, 5, enc);
        BenchTime steady = bench_dispatch(c.q, 5, STEADY_ITERS, enc);
        KernelBench kb;
        kb.name = name;
        kb.single_gbps = raw_bytes/1e9/single.best_s;
        kb.steady_gbps = raw_bytes/1e9/steady.mean_s;
        results.push_back(kb);
        fprintf(stderr, "%-28s single-batch: %8.3f GB/s (%.1f ns/4KB)   steady-state(%u): %8.3f GB/s (%.1f ns/4KB)\n",
                name, kb.single_gbps, ns_per_4kb(kb.single_gbps), STEADY_ITERS, kb.steady_gbps, ns_per_4kb(kb.steady_gbps));
    };

    run_bench("huff_decode_rows", [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.huff_decode];
        [e setBuffer:b_huff_payload offset:0 atIndex:0];
        [e setBuffer:b_huff_offsets offset:0 atIndex:1];
        [e setBuffer:b_huff_lut offset:0 atIndex:2];
        [e setBuffer:b_out_huff offset:0 atIndex:3];
        [e setBytes:&hp length:sizeof(hp) atIndex:4];
        [e setThreadgroupMemoryLength:lut_tg_alloc atIndex:0];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(ILI_ROWS_PER_TG,1,1)];
    });

    run_bench("int4_unpack_rows", [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.int4_decode];
        [e setBuffer:b_flat_packed offset:0 atIndex:0];
        [e setBuffer:b_out_int4 offset:0 atIndex:1];
        [e setBytes:&rp length:sizeof(rp) atIndex:2];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
    });

    run_bench("huff_decode_gemv_fused", [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.huff_gemv];
        [e setBuffer:b_huff_payload offset:0 atIndex:0];
        [e setBuffer:b_huff_offsets offset:0 atIndex:1];
        [e setBuffer:b_huff_lut offset:0 atIndex:2];
        [e setBuffer:b_x offset:0 atIndex:3];
        [e setBuffer:b_scale offset:0 atIndex:4];
        [e setBuffer:b_y_huff offset:0 atIndex:5];
        [e setBytes:&hp length:sizeof(hp) atIndex:6];
        [e setThreadgroupMemoryLength:lut_tg_alloc atIndex:0];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(ILI_ROWS_PER_TG,1,1)];
    });

    run_bench("int4_gemv_fused_baseline", [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.int4_gemv];
        [e setBuffer:b_flat_packed offset:0 atIndex:0];
        [e setBuffer:b_x offset:0 atIndex:1];
        [e setBuffer:b_scale offset:0 atIndex:2];
        [e setBuffer:b_y_int4 offset:0 atIndex:3];
        [e setBytes:&rp length:sizeof(rp) atIndex:4];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
    });

    run_bench("bitplane_decode_rows(main)", [&](id<MTLComputeCommandEncoder> e){
        [e setComputePipelineState:c.bitplane_decode];
        [e setBuffer:b_bp_payload_m offset:0 atIndex:0];
        [e setBuffer:b_bp_offsets_m offset:0 atIndex:1];
        [e setBuffer:b_out_bp_m offset:0 atIndex:2];
        [e setBytes:&bpp_main length:sizeof(bpp_main) atIndex:3];
        [e dispatchThreads:MTLSizeMake(TOTAL_ROWS,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
    });

    /* --------------------------------------------------- 9. verdict --- */
    double huff_decode_steady = results[0].steady_gbps;
    double huff_gemv_steady   = results[2].steady_gbps;
    double int4_gemv_steady   = results[3].steady_gbps;
    double gemv_ratio = int4_gemv_steady>0 ? huff_gemv_steady/int4_gemv_steady : 0.0;

    bool mode1_5_revived = huff_decode_steady >= 10.0;
    bool mode3_viable    = gemv_ratio >= 0.60;

    printf("\n================ PREREGISTERED VERDICT (Metal row-decode probe) ================\n");
    printf("Line A (mode-1.5): sustained Huffman decode-only >= 10 GB/s : measured %.3f GB/s -> %s\n",
           huff_decode_steady, mode1_5_revived ? "PASS (mode-1.5 REVIVED)" : "FAIL");
    printf("Line B (mode-3):   fused decode-GEMV >= 60%% of plain int4-GEMV : measured %.1f%% (%.3f vs %.3f GB/s) -> %s\n",
           gemv_ratio*100.0, huff_gemv_steady, int4_gemv_steady, mode3_viable ? "PASS (mode-3 VIABLE)" : "FAIL");
    if(!mode1_5_revived && !mode3_viable)
        printf("BOTH LINES MISS -> entropy coding is DEAD on this hardware for these formats. Recorded, stopping.\n");
    else
        printf("At least one preregistered line PASSED -- see results.md for the full writeup.\n");
    printf("==================================================================================\n");

    return 0;
}
}
