import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


C_DIR = Path(__file__).resolve().parents[1]
GENERATOR = C_DIR / "tools" / "gen_m5max_engine.py"
SOURCE = C_DIR / "glm.c"


class M5MaxEngineGeneratorTest(unittest.TestCase):
    def test_real_glm_uses_reusable_dynamic_attention_scratch(self):
        with tempfile.TemporaryDirectory() as td:
            output = Path(td) / "glm_m5max.c"
            subprocess.run(
                [sys.executable, str(GENERATOR), str(SOURCE), str(output)],
                check=True,
            )
            generated = output.read_text()

        self.assertIsNone(
            re.search(r"\bfloat\s+sc\s*\[\s*8192\s*\]", generated)
        )
        allocation = (
            "m5_attn_scores((size_t)omp_get_max_threads()*(size_t)sc_cap)"
        )
        self.assertEqual(generated.count(allocation), 2)
        self.assertNotIn("free(sc_all)", generated)

        self.assertTrue(
            generated.startswith(
                "/* Generated by tools/gen_m5max_engine.py; do not edit directly. */"
            )
        )
        self.assertIn("static _Thread_local M5RopeSlot g_m5_rope[8];", generated)
        self.assertIn(
            "static _Thread_local M5MoeScratch g_m5_moe_scratch;", generated
        )


if __name__ == "__main__":
    unittest.main()
